SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
SET default_tablespace = '';
SET default_table_access_method = heap;

CREATE TABLE public.analytics_events (
                                         id bigint NOT NULL,
                                         "timestamp" timestamp(6) without time zone,
                                         vehicle_id bigint,
                                         category character varying(255),
                                         description character varying(255),
                                         event_name character varying(255),
                                         event_type character varying(255),
                                         parameter character varying(255),
                                         user_login character varying(255)
);

ALTER TABLE public.analytics_events OWNER TO postgres;

ALTER TABLE public.analytics_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.analytics_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );

CREATE TABLE public.app_users (
                                  id bigint NOT NULL,
                                  password character varying(255) NOT NULL,
                                  role character varying(255) NOT NULL,
                                  username character varying(255) NOT NULL
);


ALTER TABLE public.app_users OWNER TO postgres;

ALTER TABLE public.app_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );

CREATE TABLE public.destinations (
                                     latitude double precision NOT NULL,
                                     longitude double precision NOT NULL,
                                     id bigint NOT NULL,
                                     name character varying(255) NOT NULL
);


ALTER TABLE public.destinations OWNER TO postgres;

ALTER TABLE public.destinations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.destinations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );

CREATE TABLE public.drivers (
                                assigned_vehicle_id bigint,
                                id bigint NOT NULL,
                                contact character varying(255),
                                full_name character varying(255) NOT NULL
);

ALTER TABLE public.drivers OWNER TO postgres;

ALTER TABLE public.drivers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.drivers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );

CREATE TABLE public.repairs (
                                cost numeric(10,2) NOT NULL,
                                repair_date date NOT NULL,
                                id bigint NOT NULL,
                                vehicle_id bigint NOT NULL,
                                description character varying(255) NOT NULL
);

ALTER TABLE public.repairs OWNER TO postgres;

ALTER TABLE public.repairs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.repairs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );

CREATE TABLE public.telematics_alerts (
                                          financial_loss numeric(10,2),
                                          latitude double precision,
                                          longitude double precision,
                                          id bigint NOT NULL,
                                          "timestamp" timestamp(6) without time zone NOT NULL,
                                          vehicle_id bigint NOT NULL,
                                          description character varying(255),
                                          type character varying(255) NOT NULL
);


ALTER TABLE public.telematics_alerts OWNER TO postgres;

ALTER TABLE public.telematics_alerts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.telematics_alerts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );

CREATE TABLE public.telematics_data (
                                        fuel_level double precision NOT NULL,
                                        latitude double precision NOT NULL,
                                        longitude double precision NOT NULL,
                                        speed double precision,
                                        temperature double precision,
                                        id bigint NOT NULL,
                                        "timestamp" timestamp(6) without time zone NOT NULL,
                                        trip_id bigint,
                                        vehicle_id bigint NOT NULL,
                                        weather_condition character varying(255)
);

ALTER TABLE public.telematics_data OWNER TO postgres;

ALTER TABLE public.telematics_data ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.telematics_data_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );

CREATE TABLE public.telemetry_data (
                                       id bigint NOT NULL,
                                       vehicle_id bigint NOT NULL,
                                       latitude double precision,
                                       longitude double precision,
                                       speed double precision,
                                       fuel_level double precision,
                                       "timestamp" timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE public.telemetry_data OWNER TO postgres;

COMMENT ON TABLE public.telemetry_data IS 'История телеметрических координат и параметров уровня топлива транспортных средств';

CREATE SEQUENCE public.telemetry_data_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.telemetry_data_id_seq OWNER TO postgres;

ALTER SEQUENCE public.telemetry_data_id_seq OWNED BY public.telemetry_data.id;

CREATE TABLE public.trips (
                              fuel_cost numeric(10,2),
                              fuel_used numeric(7,2) NOT NULL,
                              mileage_end integer NOT NULL,
                              mileage_start integer NOT NULL,
                              trip_date date NOT NULL,
                              driver_id bigint NOT NULL,
                              end_time timestamp(6) without time zone,
                              id bigint NOT NULL,
                              start_time timestamp(6) without time zone,
                              vehicle_id bigint NOT NULL,
                              status character varying(255) NOT NULL
);

ALTER TABLE public.trips OWNER TO postgres;

ALTER TABLE public.trips ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trips_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );

CREATE TABLE public.vehicles (
                                 current_fuel_level double precision,
                                 fuel_norm numeric(5,2) NOT NULL,
                                 last_latitude double precision,
                                 last_longitude double precision,
                                 manufacture_year integer NOT NULL,
                                 tank_capacity double precision,
                                 id bigint NOT NULL,
                                 model character varying(255) NOT NULL,
                                 plate_number character varying(255) NOT NULL,
                                 status character varying(255) DEFAULT 'СВОБОДЕН'::character varying NOT NULL
);

ALTER TABLE public.vehicles OWNER TO postgres;

ALTER TABLE public.vehicles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vehicles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );

ALTER TABLE ONLY public.telemetry_data ALTER COLUMN id SET DEFAULT nextval('public.telemetry_data_id_seq'::regclass);

ALTER TABLE ONLY public.analytics_events
    ADD CONSTRAINT analytics_events_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.app_users
    ADD CONSTRAINT app_users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.app_users
    ADD CONSTRAINT app_users_username_key UNIQUE (username);

ALTER TABLE ONLY public.destinations
    ADD CONSTRAINT destinations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.drivers
    ADD CONSTRAINT drivers_assigned_vehicle_id_key UNIQUE (assigned_vehicle_id);

ALTER TABLE ONLY public.drivers
    ADD CONSTRAINT drivers_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.repairs
    ADD CONSTRAINT repairs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.telematics_alerts
    ADD CONSTRAINT telematics_alerts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.telematics_data
    ADD CONSTRAINT telematics_data_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.telemetry_data
    ADD CONSTRAINT telemetry_data_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.trips
    ADD CONSTRAINT trips_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.vehicles
    ADD CONSTRAINT vehicles_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.vehicles
    ADD CONSTRAINT vehicles_plate_number_key UNIQUE (plate_number);

CREATE INDEX idx_telemetry_vehicle_time ON public.telemetry_data USING btree (vehicle_id, "timestamp");

ALTER TABLE ONLY public.telematics_alerts
    ADD CONSTRAINT fk8i1b6165hgjps0dbcu2j05uo FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id);

ALTER TABLE ONLY public.trips
    ADD CONSTRAINT fkaq8aob3mymsvmh1fkko7k9ql9 FOREIGN KEY (driver_id) REFERENCES public.drivers(id);

ALTER TABLE ONLY public.telematics_data
    ADD CONSTRAINT fkh7ixslv1ttrw0xypfe5jam5q6 FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id);

ALTER TABLE ONLY public.analytics_events
    ADD CONSTRAINT fkq8k7vc2dmfy0bwhycu75k6504 FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id);

ALTER TABLE ONLY public.trips
    ADD CONSTRAINT fkqahsaodjirbk4if91c9bfnlgg FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id);

ALTER TABLE ONLY public.drivers
    ADD CONSTRAINT fkqjq0nt36sfrvo1de5l1ksxgro FOREIGN KEY (assigned_vehicle_id) REFERENCES public.vehicles(id);

ALTER TABLE ONLY public.telematics_data
    ADD CONSTRAINT fkr77wkc7u22e8e3jrln9q1xng5 FOREIGN KEY (trip_id) REFERENCES public.trips(id);


ALTER TABLE ONLY public.repairs
    ADD CONSTRAINT fkr8rwhlbv43kxbn4j93hkul7ax FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id);

GRANT ALL ON SCHEMA public TO transport_user;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.analytics_events TO transport_user;

GRANT SELECT,USAGE ON SEQUENCE public.analytics_events_id_seq TO transport_user;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.app_users TO transport_user;

GRANT SELECT,USAGE ON SEQUENCE public.app_users_id_seq TO transport_user;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.destinations TO transport_user;

GRANT SELECT,USAGE ON SEQUENCE public.destinations_id_seq TO transport_user;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.drivers TO transport_user;

GRANT SELECT,USAGE ON SEQUENCE public.drivers_id_seq TO transport_user;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.repairs TO transport_user;

GRANT SELECT,USAGE ON SEQUENCE public.repairs_id_seq TO transport_user;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.telematics_alerts TO transport_user;

GRANT SELECT,USAGE ON SEQUENCE public.telematics_alerts_id_seq TO transport_user;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.telematics_data TO transport_user;

GRANT SELECT,USAGE ON SEQUENCE public.telematics_data_id_seq TO transport_user;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.telemetry_data TO transport_user;

GRANT SELECT,USAGE ON SEQUENCE public.telemetry_data_id_seq TO transport_user;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.trips TO transport_user;

GRANT SELECT,USAGE ON SEQUENCE public.trips_id_seq TO transport_user;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.vehicles TO transport_user;

GRANT SELECT,USAGE ON SEQUENCE public.vehicles_id_seq TO transport_user;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT,USAGE ON SEQUENCES TO transport_user;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT,INSERT,DELETE,UPDATE ON TABLES TO transport_user;