server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/transport_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

openweathermap.api.url=https://api.openweathermap.org/data/2.5/weather
openweathermap.api.key=${OPENWEATHER_API_KEY}

fuelprice.api.url=https://api.collectapi.com/economy/gasPrice
fuelprice.api.key=${FUEL_API_KEY}

google.maps.api.url=https://maps.googleapis.com/maps/api/geocode/json
google.maps.api.key=${GOOGLE_MAPS_API_KEY}

telematics.speed.limit=90.0

telematics.fuel.drop.threshold=5.0